-- Drop all policies
DROP POLICY IF EXISTS users_select_own ON public.users;
DROP POLICY IF EXISTS users_update_own ON public.users;
DROP POLICY IF EXISTS resumes_select_own ON public.resumes;
DROP POLICY IF EXISTS resumes_insert_own ON public.resumes;
DROP POLICY IF EXISTS resumes_update_own ON public.resumes;
DROP POLICY IF EXISTS resumes_delete_own ON public.resumes;
DROP POLICY IF EXISTS premium_features_select_own ON public.premium_features;
DROP POLICY IF EXISTS premium_features_insert_own ON public.premium_features;
DROP POLICY IF EXISTS premium_features_update_own ON public.premium_features;
DROP POLICY IF EXISTS ats_scores_select_own ON public.ats_scores;
DROP POLICY IF EXISTS ats_scores_insert_own ON public.ats_scores;
DROP POLICY IF EXISTS ats_scores_update_own ON public.ats_scores;
DROP POLICY IF EXISTS interview_tips_select_own ON public.interview_tips;
DROP POLICY IF EXISTS interview_tips_insert_own ON public.interview_tips;
DROP POLICY IF EXISTS interview_tips_update_own ON public.interview_tips;
DROP POLICY IF EXISTS service_role_all_resumes ON public.resumes;
DROP POLICY IF EXISTS service_role_all_premium_features ON public.premium_features;
DROP POLICY IF EXISTS service_role_all_ats_scores ON public.ats_scores;
DROP POLICY IF EXISTS service_role_all_interview_tips ON public.interview_tips;
DROP POLICY IF EXISTS "Users can view their own resumes" ON public.resumes;
DROP POLICY IF EXISTS "Users can update their own resumes" ON public.resumes;
DROP POLICY IF EXISTS "Users can insert their own resumes" ON public.resumes;
DROP POLICY IF EXISTS "Service role can manage all resumes" ON public.resumes;
DROP POLICY IF EXISTS "Users can view their own data" ON public.users;
DROP POLICY IF EXISTS "Users can update their own data" ON public.users;
DROP POLICY IF EXISTS "Users can view their own premium features" ON public.premium_features;
DROP POLICY IF EXISTS "Service role can manage all premium features" ON public.premium_features;
DROP POLICY IF EXISTS "Users can view ats scores for their resumes" ON public.ats_scores;
DROP POLICY IF EXISTS "Service role can manage all ats scores" ON public.ats_scores;
DROP POLICY IF EXISTS "Users can view interview tips for their resumes" ON public.interview_tips;
DROP POLICY IF EXISTS "Service role can manage all interview tips" ON public.interview_tips; 